import Head from 'next/head'
import Mydetails from './components/Mydetails'
import TypewriterCompornent from './components/Typewriter'
import Modal from './components/Modal'
import Timestamp from './components/Timestamp'



export default function Home() {

  const test = {

  }

  return (
    <>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='relative w-screen h-screen bg-slate-200 font-Lora font-custom'>

        <div className='wrapper font-bold'>
          <Timestamp/>
          <div className='text-5xl relative h-full'>
            <TypewriterCompornent />
          </div>
        </div>

        <div className='wrapper flex flex-wrap justify-center'>

{/*
TODO

Create button & UI

after

create logics of modalwindow & closeModalwindow func.


 */}

          <div className="button">
            <p className='text-4xl'>詳細情報</p>
          </div>
          <div className="button">
            <p className='text-4xl'>好きなもの・趣味</p>
          </div>
          <div className="button">
            <p className='text-4xl'>経歴</p>
          </div>
          <div className="button">
            <p className='text-4xl'>苦手なもの</p>
          </div>

          {/* <Modal title={"詳細"}>
              <p>生年月日: 1997-08-06</p>
              <p>年齢: 25</p>
              <p>血液型: B型</p>
              <p>出生地: 長野県</p>
              <p>居住地: 京都府京丹後市峰山町</p>
              <p>卒業学校: 静岡県立田方農業高等学校</p>
              <p>身長: 172cm</p>
              <p>獅子座、丑年</p>
          </Modal> */}

          <div className="">

            <Mydetails title={"詳細情報"}>
              <p>生年月日: 1997-08-06</p>
              <p>年齢: 25</p>
              <p>血液型: B型</p>
              <p>出生地: 長野県</p>
              <p>居住地: 京都府京丹後市峰山町</p>
              <p>卒業学校: 静岡県立田方農業高等学校</p>
              <p>身長: 172cm</p>
              <p>獅子座、丑年</p>
            </Mydetails>

          </div>

          <Mydetails title={"好きなもの・趣味"}>
            <p>本を読むことが趣味です。ジャンルは様々ですが、主に心理学、恋愛小説、ノンフィクション、戦争関係が多いです。</p>
            <p>最近読んだ本の中で非常に面白かったのは「夜と霧」という強制収用のお話です</p>
            <p>紅茶を茶葉で買い、家で淹れるのが好きです</p>
            <p>実家では猫を飼っていました。猫派です</p>
            <p>次はハリネズミをお迎えしたいと思ってます</p>
            <p>ゲームもします。基本はFPSをやります。</p>
            <p>しかし積みゲーがたくさんあって勉強とどのように並行しようか考え中です</p>
          </Mydetails>

          <Mydetails title={"経歴"}>
            <p>静岡県立田方農業高等学校を卒業後</p>
            <p>静岡県東部でフランチャイズ展開している企業の飲食店に就職</p>
            <p>料理全般できるようになりました。</p>
            <p>その後、Appleの正規販売代理店で販売員として従事</p>
            <p>コロナの影響により、解雇</p>
            <p>そして現在交際中の女性と出会い、京都に移住することを決断</p>
          </Mydetails>

          <Mydetails title={"苦手なもの"}>
            <p>海亀のスープ（本当に苦手です）</p>
            <p>オリーブの実（この世の食べ物ではありません）</p>
            <p>貝類</p>
          </Mydetails>

          </div>{/* container end */}

        <div className='container'>
          {/* このボタンを押すと、Thxメッセージを出して、自動でタブを閉じる */}
          <button>exit</button>
        </div>

    </main>

    </>
  )
}
